runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:oklBIcCgZFQq3yEIKT83IHRzpAucKq3+gyJA1rDeHnE=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: file

  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3306
  DB_DATABASE: coffeemate
  DB_USERNAME: root
  DB_PASSWORD: coffeemateroot
  DB_SOCKET: /cloudsql/coffeemate-254917:asia-east1:coffeemate

beta_settings:
  cloud_sql_instances: coffeemate-254917:asia-east1:coffeemate
