# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.3.9

pipelines:
  default:
    - step:
        name: Validate
        caches:
          - global-composer-vendor
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
#          - vendor/bin/phpunit

    - step:
        name: Deploy to `Staging`
        deployment: staging
        trigger: manual
        caches:
          - global-composer-vendor
          - composer
        script:
          - apt-get update && apt-get install -y unzip git git-core libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/*
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGING.git HEAD:master
          
    - step:
        name: Deploy to `Production`
        deployment: production
        trigger: manual
        caches:
          - global-composer-vendor
          - composer
        script:
          - apt-get update && apt-get install -y unzip git git-core libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/*
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git HEAD:master
definitions:
  caches:
    global-composer-vendor: ~/.composer/vendor
